name: Automatização de Processo

on:
  push:
    branches:
      - main  
jobs:
  automatizar:
    runs-on: windows-latest  
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  

      - name: Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install pandas pyautogui

      - name: Executar Script de Automação
        run: |
          python script_de_automacao.py  # ajuste para o nome do seu script Python